name: Daily Commit Bot

on:
  schedule:
    - cron: "30 5 * * *"  # Runs daily at 5:30 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Step with email 25ds1000057@ds.study.iitm.ac.in
        run: echo "This step includes my email."

      - name: Make a change
        run: |
          echo "$(date)" >> daily_log.txt

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "github-actions@github.com"
          git add daily_log.txt
          git commit -m "Daily commit: $(date)" || exit 0
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main
